### ISSUE TITLE
Hide the WYSIWYG content editor where it's not needed

### ISSUE THREAD

**Issue by mandiwise** [redacademy/citystudio-winter-2016#7]
Be sure to hide the default WYSIWYG editor if it's not needed for a particular post type. It will be confusing for the end user if they add content to this box and it doesn't show up anywhere on the front end.

You can do that by removing support the `editor` where you register your custom post type (in your functionality plugin) or by ticking this box where you create your field group in CFS:

<img width="365" alt="content-editor" src="https://cloud.githubusercontent.com/assets/1518780/14198375/5999dde4-f78e-11e5-9385-6884d9634bc4.png">

**Comment by rivaadara111** [comment]
hid this ish by ticking the box
